
- hosts: localhost
  vars:
  - aws_akey:
  - aws_skey:
  - ec2_url:
  - zone1:
  - zone2:
  - vol_size:

  tasks:
  - name: create volume
    ec2_vol: volume_size={{ vol_size }} zone={{ zone1 }} aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}
    register: volume

  - name: delete volume
    ec2_vol: id={{ volume['volume_id'] }} state=absent aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}

  - name: create volume
    ec2_vol: volume_size={{ vol_size }} zone={{ zone1 }} aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}
    register: volume

  - name: create snapshot
    ec2_snapshot: volume_id={{ volume['volume_id'] }} wait=yes aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}
    register: snap

  - name: create volume from snapshot
    ec2_vol: zone={{ zone1 }} snapshot={{ snap['snapshot_id'] }} volume_size={{ snap['volume_size'] }} aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}
    register: newvolume

  - name: delete new volume
    ec2_vol: id={{ newvolume['volume_id'] }} state=absent aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}

# available in ansible 1.9 only
#  - name: delete snapshot
#    ec2_snapshot: snapshot_id={{ snap['snapshot_id'] }} state=absent aws_access_key={{ aws_akey }} aws_secret_key={{ aws_skey }} ec2_url={{ ec2_url }}

  - name: shell snapshot deletion
    shell: euca-delete-snapshot {{ snap['snapshot_id'] }} -I {{ aws_akey }} -S {{ aws_skey }} -U {{ ec2_url }}
